### ISSUE TITLE
Struct parser errors expecting '*mem.Allocator.VTable'

### ISSUE THREAD

**Issue by ryzech** [sam701/zig-toml#12] opened 2024-10-18 03:11 UTC
Attempting to parse a struct results in the following error:
```
/home/ryzechdev/.local/share/zigdown/zig-0.14.0-dev.1939+816dfca0b/files/lib/std/mem/Allocator.zig:104:17: error: no size available for type 'anyopaque'
    if (@sizeOf(T) == 0) return @as(*T, @ptrFromInt(math.maxInt(usize)));
                ^
/home/ryzechdev/.local/share/zigdown/zig-0.14.0-dev.1939+816dfca0b/files/lib/std/mem/Allocator.zig:115:17: error: no size available for type 'anyopaque'
    if (@sizeOf(T) == 0) return;
                ^
/home/ryzechdev/.cache/zig/p/122078852760edc51542425347595a5425e8a7291f185d4dedaad51da984927e286a/src/struct_mapping.zig:121:59: error: expected type '*mem.Allocator.VTable', found '*const mem.Allocator.VTable'
                    return setValue(ctx, tinfo.child, dest.*, value);
                                                      ~~~~^~
/home/ryzechdev/.cache/zig/p/122078852760edc51542425347595a5425e8a7291f185d4dedaad51da984927e286a/src/struct_mapping.zig:121:59: note: cast discards const qualifier
/home/ryzechdev/.cache/zig/p/122078852760edc51542425347595a5425e8a7291f185d4dedaad51da984927e286a/src/struct_mapping.zig:53:52: note: parameter type declared here
fn setValue(ctx: *Context, comptime T: type, dest: *T, value: *const Value) !void {
```

This is the code that results in the error:
```zig
var parser = toml.Parser(config.GenerationConfig).init(allocator);
defer parser.deinit();

var result = parser.parseFile(full_path) catch |err| {
    log.failure("Failed to parse file: \"{s}\" {any}", .{
        full_path,
        err,
    });
    posix.exit(1);
};
defer result.deinit();
```
    
Zig Version: `0.14.0-dev.1939+816dfca0b`

I could just be doing something wrong, but everything looked right to me, relatively similar to the example besides the `catch`.

The allocator is defined as
```zig
var gpa = std.heap.GeneralPurposeAllocator(.{}){};
const allocator = gpa.allocator();
```

Which is the same as the example as well, but that shouldn't make a difference regardless.

**Comment by sam701** [comment] 2024-10-18 06:30
Could you share the struct so that I can reproduce it?

Looking at this error line... can it be that your struct contains a const field (`*const mem.Allocator.VTable`)? An allocator inside a config struct is also strange. Anyway, please share your config struct (or a part of it), it will be helpful 🙂  
```
/home/ryzechdev/.cache/zig/p/122078852760edc51542425347595a5425e8a7291f185d4dedaad51da984927e286a/src/struct_mapping.zig:121:59: error: expected type '*mem.Allocator.VTable', found '*const mem.Allocator.VTable'
                    return setValue(ctx, tinfo.child, dest.*, value);
                                                      ~~~~^~
```

**Comment by ryzech** [comment] 2024-10-18 06:36
Sure! I did see that HashMaps weren't supported when I looked through the issues after i created the issue, so potentially that could be it? But the error doesn't mention that, so maybe not.
```zig
pub const SystemPackage = struct {
    packages: [][]const u8,
};

pub const GenerationConfig = struct {
    imports: [][]const u8,
    systems: std.StringHashMap(SystemPackage),
};
```

**Comment by sam701** [comment] 2024-10-18 06:53
Ah, yes, you are right, it's a duplicate of #9 

For now only `toml.Table` is available. I'll try to look into that issue next days.

**Closed by sam701** 2024-10-18 06:53 UTC

**Comment by sam701** [comment] 2024-10-18 20:16
@ryzech Implemented, please take a look at the test in this commit https://github.com/sam701/zig-toml/commit/88e6196370eb8c9c70220ee86349504640626ed4
